### ISSUE TITLE
Python 2.7 backport

### ISSUE THREAD

**Issue by britram** [britram/python-ipfix#2]
coordinate with / investigate joelparker fork to backport to 2.7

**Comment by britram** [comment]
@brettdh thanks for #16, will look into merging for 0.9.8...

**Comment by britram** [comment]
in develop-merge-27, need to verify a couple of things with the tests, will revisit this roll a 0.9.8 next week.

thanks and apologies for the short delay in merging... :)

**Comment by jklahn** [comment]
Python 2.7.14
ipfix 0.9.7

Steps to reproduce:
```
pip install functools32
pip install py2-ipaddress
pip install pytz
pip install ipfix

- Attempt to import ipfix produces and import error:
[root@91888e677db3 tests]# python
Python 2.7.14 (default, Sep 28 2017, 16:40:48) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipfix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ipfix/__init__.py", line 54, in <module>
    from . import types
  File "/usr/local/lib/python2.7/site-packages/ipfix/types.py", line 148, in <module>
    from datetime import datetime, timedelta, timezone
ImportError: cannot import name timezone
```
Note: Python 2.7 `datetime` library does not include a `timezone` module
```
[root@91888e677db3 tests]# python
Python 2.7.14 (default, Sep 28 2017, 16:40:48) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from dateime import timezone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named dateime
```

**Comment by JackSunshine** [comment]
Hi, I'd like to know Is any update about this?

Thanks
